### ISSUE TITLE
Trouble running the demo

### ISSUE THREAD

**Issue by ckygel** [buckie/juno#27]
I'm using Ubuntu 16.04 LTS on Virtual Box.

the build works, but when trying to run ./junoclient.sh it throws

rlwrap: error: Cannot execute junoclient: No such file or directory.

Any troubleshooting would be helpful, and will contribute to adding details to project!
Thanks :)

**Comment by buckie** [comment]
You probably need to make a `./log` folder. Also, if you install `tmux <= 2.0` you can use `./demo/start.sh` from within a tmux session.

**Comment by ckygel** [comment]
I'm running on tmux 2.0, still having the same issue. Some google answers say it has to do with incompatibility between 32bit and 64 bit; do you know the system the demo was tested on? Maybe I will just try to replicate the same environment.

**Comment by buckie** [comment]
I'm relatively sure that you'll have a lot of issues if you try running on a 32bit system. Juno uses a pretty advance concurrent channel system that needs specific x86_64 ASM instructions to work. 

Can you paste the results of running this command: `stack build && stack exec -- junoserver +RTS -N4 -T -RTS -c conf/10000-cluster.yaml --apiPort 8000`

**Comment by ckygel** [comment]
ckylee@ckylee-VirtualBox:~/Downloads/juno-develop$ stack build && stack exec -- junoserver +RTS -N4 -T -RTS -c conf/10000-cluster.yaml --apiPort 8000
vector-algorithms-0.7.0.1: configure
vector-algorithms-0.7.0.1: build
Progress: 1/46
--  While building package vector-algorithms-0.7.0.1 using:
      /home/ckylee/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/ckylee/Downloads/juno-develop/.stack-work/logs/vector-algorithms-0.7.0.1.log

```
Configuring vector-algorithms-0.7.0.1...
Building vector-algorithms-0.7.0.1...
Preprocessing library vector-algorithms-0.7.0.1...
[ 1 of 10] Compiling Data.Vector.Algorithms.Common ( src/Data/Vector/Algorithms/Common.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Data/Vector/Algorithms/Common.o )
[ 2 of 10] Compiling Data.Vector.Algorithms.Radix ( src/Data/Vector/Algorithms/Radix.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Data/Vector/Algorithms/Radix.o )
[ 3 of 10] Compiling Data.Vector.Algorithms.Search ( src/Data/Vector/Algorithms/Search.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Data/Vector/Algorithms/Search.o )
[ 4 of 10] Compiling Data.Vector.Algorithms.Optimal ( src/Data/Vector/Algorithms/Optimal.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Data/Vector/Algorithms/Optimal.o )
[ 5 of 10] Compiling Data.Vector.Algorithms.Insertion ( src/Data/Vector/Algorithms/Insertion.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Data/Vector/Algorithms/Insertion.o )
[ 6 of 10] Compiling Data.Vector.Algorithms.AmericanFlag ( src/Data/Vector/Algorithms/AmericanFlag.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Data/Vector/Algorithms/AmericanFlag.o )
[ 7 of 10] Compiling Data.Vector.Algorithms.Tim ( src/Data/Vector/Algorithms/Tim.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Data/Vector/Algorithms/Tim.o )
ghc: out of memory (requested 2097152 bytes)
```

**Comment by buckie** [comment]
Thanks. Your build is failing, I have the same issues when running on T2.micro's on AWS. If you give your VM 4GB RAM it should finish the build... google around for how to do this (it'll be in VB's settings for the image you're running but I'm not sure where). After you've done that, retry the command and paste in the results.

When you hit dependency issues, like having the wrong version of zeromq, have a look here for what to do. https://github.com/kadena-io/juno/blob/develop/.travis.yml

Keep in mind that you need some deps in ubuntu installed and the `zeromq3-dev` that you get by default through `apt-get` is the wrong version (3.x) where as you'll need (4.x). This will fix that issue, and install the other deps you need (I think, not sure of the complete list for ubuntu):

```
#!/bin/sh
cd ~
sudo apt-get remove --purge libzmq3-dev
sudo add-apt-repository -y ppa:chris-lea/zeromq
sudo apt-get update
sudo apt-get install -y libzmq3-dev pkg-config
stack setup
```

**Comment by ckygel** [comment]
Thanks for the help! I got it running (although I got the wrong version of tmux, it still runs).

I was missing a specific zlib package called zlib1g-dev that was stopping from building.

If anyone's having "Missing (or bad) header file: zlib.h" problem, try:

`sudo apt-get install zlib1g-dev`
