### ISSUE TITLE
tmux version 2.1 not supported

### ISSUE THREAD

**Issue by jrthom18** [buckie/juno#3]
Looks like there is an issue running the demo if installing on Mac and using brew to install tmux. Must manually install an older version of tmux <= 1.8 appears to work.

**Comment by buckie** [comment]
Wow... it is really broken on `tmux 2.1`. I just spent an hour trying to figure it out and had exactly zero luck. It seems that for now only `tmux 2.0` is guaranteed to work (the version I use). If you can figure out how to fix the script to get it running on 2.1 please let me know.

**Comment by slpopejoy** [comment]
hmm ... works for me on tmux 2.1 ...

**Comment by slpopejoy** [comment]
I installed tmux 2.1 months ago, so maybe something about the brew formula changed?

**Comment by slpopejoy** [comment]
Uninstalled, reinstalled, still works.

**Comment by slpopejoy** [comment]
Demo does not work from within tmux; start tmux, then in another terminal session run the demo.
